### ISSUE TITLE
Dima throws exception with a very small Jaccard similarity threshold

### ISSUE THREAD

**Issue by wangzk** [TsinghuaDatabaseGroup/Dima#4]
When I ran Dima with a very small Jaccard similarity threshold (<1e-10), Dima threw the following exception and failed to finish:

```
Job aborted due to stage failure: Task 2 in stage 13.0 failed 4 times, most recent failure: Lost task 2.3 in stage 13.0 (TID 64, slave003): java.lang.ArrayIndexOutOfBoundsException: 0
	at org.apache.spark.sql.execution.joins.JaccardSimilarityJoin.heapExtractMin(JaccardSimilarityJoin.scala:178)
	at org.apache.spark.sql.execution.joins.JaccardSimilarityJoin$$anonfun$calculateVsl$1.apply$mcVI$sp(JaccardSimilarityJoin.scala:359)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at org.apache.spark.sql.execution.joins.JaccardSimilarityJoin.calculateVsl(JaccardSimilarityJoin.scala:358)
	at org.apache.spark.sql.execution.joins.JaccardSimilarityJoin$$anonfun$partition_r$1.apply(JaccardSimilarityJoin.scala:425)
	at org.apache.spark.sql.execution.joins.JaccardSimilarityJoin$$anonfun$partition_r$1.apply(JaccardSimilarityJoin.scala:402)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at org.apache.spark.sql.execution.joins.JaccardSimilarityJoin.partition_r(JaccardSimilarityJoin.scala:402)
	at org.apache.spark.sql.execution.joins.JaccardSimilarityJoin$$anonfun$48.apply(JaccardSimilarityJoin.scala:760)
	at org.apache.spark.sql.execution.joins.JaccardSimilarityJoin$$anonfun$48.apply(JaccardSimilarityJoin.scala:759)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:126)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

[The code that I ran](https://gist.github.com/wangzk/ddf8b657becaf7f2b6a6e2204df295fd) is derived from the DataFrame example code.

The data set that I used can be downloaded from [here](https://www.jianguoyun.com/p/DS-MTZMQ3xwY-aJA).

I ran the program with the following command line:

```shell
spark-submit --master spark://slave001:7078 --executor-memory 20g --driver-memory 20g --num-executors 4 ./dima-jaccard_2.10-1.0.jar dblp.adj.file                
```

The program outputed `Threshold = 9.946317100779379E-12` and then crashed during the similarity join.

Is this a bug? Or did I run Dima in a wrong way?

Thanks for your concern!

**Comment by greatji** [comment]
Thanks for your testing

Dima may encounter overflow exception with extremely low threshold. In general use cases, Jaccard Similarity is range from 0.4 to 0.95, and record length will be no more than 1000, so we did not cover the extremely low threshold cases.

I will add some tips to help people using this project.

**Comment by wangzk** [comment]
Thanks for the quick reply :) .

Can the maximum record length limitation explain the following exception I met?

I ran Dima on the LiveJournal dataset with the threshold 0.9. The dataset I used is the collection of the adjacency sets of the LiveJournal network (http://snap.stanford.edu/data/com-LiveJournal.html).

The maximum record length (i.e. the maximum vertex degree in the network) in the dataset is 14815. It is 10 times of the record length limitation 1000.

The exception I met is:
```
java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:869)
	at org.apache.spark.storage.DiskStore$$anonfun$getBytes$2.apply(DiskStore.scala:127)
	at org.apache.spark.storage.DiskStore$$anonfun$getBytes$2.apply(DiskStore.scala:115)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1250)
	at org.apache.spark.storage.DiskStore.getBytes(DiskStore.scala:129)
	at org.apache.spark.storage.DiskStore.getBytes(DiskStore.scala:136)
	at org.apache.spark.storage.BlockManager.doGetLocal(BlockManager.scala:503)
	at org.apache.spark.storage.BlockManager.getLocal(BlockManager.scala:420)
	at org.apache.spark.storage.BlockManager.get(BlockManager.scala:625)
	at org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:154)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:78)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
One of the executors threw the exception and crashed. Other executors failed consequentially due to the `org.apache.spark.storage.BlockFetchException: Failed to fetch block from 1 locations.` error.

Do you think the exception is caused by the record length limitation?

Thanks again for consideration!

**Comment by greatji** [comment]
What's the total number of data? Too many records in one partition may exceed the upper bound that scala Array supports.

**Comment by wangzk** [comment]
The number of records is 3997962. Before the join, I repartition the input RDD into 384 partitions.
