### ISSUE TITLE
Dima threw the NegativeArraySizeException during execution

### ISSUE THREAD

**Issue by wangzk** [TsinghuaDatabaseGroup/Dima#5]
When I ran Dima on the [DBLP dataset](https://www.jianguoyun.com/p/DS-MTZMQ3xwY-aJA) with the similarity threshold 0.6, Dima threw the following serialization exception:

```
com.esotericsoftware.kryo.KryoException: java.lang.NegativeArraySizeException
Serialization trace:
data (org.apache.spark.sql.index.IPartition)
	at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:585)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:568)
	at org.apache.spark.serializer.KryoSerializationStream.writeObject(KryoSerializer.scala:194)
	at org.apache.spark.serializer.SerializationStream.writeAll(Serializer.scala:153)
	at org.apache.spark.storage.BlockManager.dataSerializeStream(BlockManager.scala:1196)
	at org.apache.spark.storage.BlockManager.dataSerialize(BlockManager.scala:1202)
	at org.apache.spark.storage.MemoryStore.putArray(MemoryStore.scala:136)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:800)
	at org.apache.spark.storage.BlockManager.putArray(BlockManager.scala:676)
	at org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:175)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:78)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NegativeArraySizeException
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.resize(IdentityObjectIntMap.java:409)
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.putStash(IdentityObjectIntMap.java:227)
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.push(IdentityObjectIntMap.java:221)
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.put(IdentityObjectIntMap.java:117)
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.putStash(IdentityObjectIntMap.java:228)
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.push(IdentityObjectIntMap.java:221)
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.put(IdentityObjectIntMap.java:117)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.addWrittenObject(MapReferenceResolver.java:23)
	at com.esotericsoftware.kryo.Kryo.writeReferenceOrNull(Kryo.java:598)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:566)
	at com.twitter.chill.Tuple2Serializer.write(TupleSerializers.scala:36)
	at com.twitter.chill.Tuple2Serializer.write(TupleSerializers.scala:33)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:568)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:318)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:293)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:568)
	at com.twitter.chill.Tuple3Serializer.write(TupleSerializers.scala:50)
	at com.twitter.chill.Tuple3Serializer.write(TupleSerializers.scala:45)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:568)
	at com.twitter.chill.Tuple2Serializer.write(TupleSerializers.scala:36)
	at com.twitter.chill.Tuple2Serializer.write(TupleSerializers.scala:33)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:568)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:318)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:293)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501)
	at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:564)
	... 18 more
```
The number of records is 317080. The maximum record length (i.e. the maximum vertex degree in the DBLP network) in the dataset is 343 .

I repartitioned the input data frames into 1152 partitions before the similarity join.

The script that I used `Dima_run_v2.scala`is available at [my gist](https://gist.github.com/wangzk/ddf8b657becaf7f2b6a6e2204df295fd). I ran the script with the arguments `dblp.adj.file 0.6 1152`.

It seems that one of the intermediate RDDs in the execution only has two partitions. The size of one partition may be too large, which makes the serializer overflows.

![image](https://user-images.githubusercontent.com/2674020/34904531-bb3bfa72-f882-11e7-97d6-a0322d7bba2d.png)

Thanks for inspecting this bug report!

**Comment by greatji** [comment]
Hi, the partition number is configurable by parameter `spark.sql.joins.numSimialrityPartitions`, and the default value is 2. We have tested the dblp data in our experiments, this data is fully supported in our environment.

**Comment by wangzk** [comment]
It works by setting `spark.sql.joins.numSimialrityPartitions` larger in my environment. Thanks a lot!
